name: Build and Deploy Function App

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'src/**'
  workflow_dispatch:

permissions:
  id-token: write # Required for Workload Identity Federation
  contents: read  # Required to checkout the code

env:
  DOTNET_VERSION: '8.0.x' # Specify your .NET version
  PROJECT_PATH: src/EventGridBlobTriggerFunction/EventGridBlobTriggerFunction.csproj

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish Function App
        run: |
          dotnet restore ${{ env.PROJECT_PATH }}
          dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
          dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./publish
          cd ./publish
          zip -r ../publish.zip .
          cd ..

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Function App to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: func-evgblobtrig-demo-westus-02
          package: ./publish.zip
          resource-group-name: rg-evgblobtrig-demo-westus2